-- Step 8: Insert Park Restaurants
INSERT INTO restaurants (
        park_id,
        name,
        restaurant_type,
        cuisine,
        location,
        price_range,
        rating,
        hours_open,
        hours_close,
        reservation_difficulty,
        specialties,
        atmosphere,
        dining_plan_accepted,
        characters
    )
SELECT p.id,
    vals.name,
    vals.restaurant_type::restaurant_type,
    vals.cuisine,
    vals.location,
    vals.price_range,
    vals.rating,
    vals.hours_open::time,
    vals.hours_close::time,
    vals.reservation_difficulty,
    vals.specialties,
    vals.atmosphere,
    vals.dining_plan_accepted,
    vals.characters
FROM parks p,
    (
        VALUES (
                'Magic Kingdom',
                'Be Our Guest Restaurant',
                'table_service',
                'French',
                'Beast''s Castle, Fantasyland',
                '$35-$65 per adult',
                4.5,
                '11:30',
                '21:30',
                'Very Hard',
                ARRAY ['Braised Pork Shoulder', 'Pan-seared Chicken', 'Ratatouille'],
                'Elegant castle dining in Beast''s enchanted castle',
                true,
                null
            ),
            (
                'Magic Kingdom',
                'Dole Whip Stand',
                'quick_service',
                'Snacks',
                'Adventureland',
                '$4-$8 per item',
                4.8,
                '09:00',
                '22:00',
                'Easy',
                ARRAY ['Dole Whip', 'Dole Whip Float', 'Pineapple Treats'],
                'Casual outdoor snack location',
                false,
                null
            ),
            (
                'EPCOT',
                'Space 220 Restaurant',
                'table_service',
                'Contemporary American',
                'Future World, EPCOT',
                '$55-$79 per adult',
                4.6,
                '11:30',
                '21:00',
                'Very Hard',
                ARRAY ['Space-themed dishes', 'Stellar views', 'Unique atmosphere'],
                'Dining 220 miles above Earth with stunning space views',
                true,
                null
            ),
            (
                'Animal Kingdom',
                'Flame Tree Barbecue',
                'quick_service',
                'BBQ',
                'Discovery Island',
                '$12-$18 per meal',
                4.4,
                '11:00',
                '19:00',
                'Easy',
                ARRAY ['Ribs', 'Pulled Pork', 'BBQ Platter'],
                'Outdoor seating with water views',
                true,
                null
            )
    ) AS vals(
        park_name,
        name,
        restaurant_type,
        cuisine,
        location,
        price_range,
        rating,
        hours_open,
        hours_close,
        reservation_difficulty,
        specialties,
        atmosphere,
        dining_plan_accepted,
        characters
    )
WHERE p.name = vals.park_name;
-- Step 9: Insert Character Dining Restaurants (associated with hotels/resorts)
INSERT INTO restaurants (
        hotel_id,
        name,
        restaurant_type,
        cuisine,
        location,
        price_range,
        rating,
        hours_open,
        hours_close,
        reservation_difficulty,
        specialties,
        atmosphere,
        dining_plan_accepted,
        characters
    )
SELECT h.id,
    vals.name,
    vals.restaurant_type::restaurant_type,
    vals.cuisine,
    vals.location,
    vals.price_range,
    vals.rating,
    vals.hours_open::time,
    vals.hours_close::time,
    vals.reservation_difficulty,
    vals.specialties,
    vals.atmosphere,
    vals.dining_plan_accepted,
    vals.characters
FROM hotels h,
    (
        VALUES (
                'Disney''s Grand Floridian Resort & Spa',
                'Ohana',
                'table_service',
                'Polynesian',
                'Disney''s Polynesian Village Resort',
                '$45-$65 per adult',
                4.7,
                '07:30',
                '22:00',
                'Hard',
                ARRAY ['Grilled Skewers', 'Bread Pudding', 'Polynesian-style Family Feast'],
                'Fun family-style dining with Polynesian entertainment',
                true,
                ARRAY ['Lilo', 'Stitch', 'Mickey', 'Pluto']
            ),
            (
                'Disney''s Grand Floridian Resort & Spa',
                'Chef Mickey''s',
                'character_dining',
                'American',
                'Disney''s Contemporary Resort',
                '$42-$62 per adult',
                4.3,
                '07:00',
                '21:30',
                'Hard',
                ARRAY ['Mickey Waffles', 'Prime Rib', 'Character Interactions'],
                'Lively buffet with Disney characters visiting tables',
                true,
                ARRAY ['Mickey Mouse', 'Minnie Mouse', 'Donald Duck', 'Goofy', 'Pluto']
            )
    ) AS vals(
        hotel_name,
        name,
        restaurant_type,
        cuisine,
        location,
        price_range,
        rating,
        hours_open,
        hours_close,
        reservation_difficulty,
        specialties,
        atmosphere,
        dining_plan_accepted,
        characters
    )
WHERE h.name = vals.hotel_name;